import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://mycar.kz/');
  await page.getByRole('banner').getByRole('link', { name: 'Поиск авто' }).click();
  await page.getByText('Выберите город').click();
  await page.getByRole('button', { name: 'Алматы' }).click();
  await page.getByText('Марка и модель').click();
  await page.getByRole('button', { name: 'Toyota Toyota', exact: true }).click();
  await page.getByRole('button', { name: 'Camry', exact: true }).click();
  await page.getByRole('button', { name: 'показать' }).click();
  await page.getByText('Поколение').click();
  await page.getByRole('button', { name: 'XV70 XV70 2017 - 2021' }).click();
  await page.getByRole('button', { name: 'Готово' }).click();
  await page.getByText('Исключить из поиска').click();
  await page.getByRole('button', { name: 'Acura Acura' }).click();
  await page.getByRole('button', { name: 'ILX' }).getByLabel('').check();
  await page.getByRole('button', { name: 'Исключить' }).click();
  await page.getByLabel('Цена, От').click();
  await page.getByLabel('Цена, От').fill('13 000 000');
  await page.locator('div').filter({ hasText: /^Цена, До$/ }).nth(1).click();
  await page.getByLabel('Цена, До').click();
  await page.getByLabel('Цена, До').fill('18 000 000');
  await page.locator('.first\\:rounded-t-lg > div > div:nth-child(3)').first().click();
  await page.getByLabel('Первоначальный взнос').click();
  await page.getByLabel('Первоначальный взнос').fill('5 000 000');
  await page.getByLabel('Ежемесячный платеж').click();
  await page.getByLabel('Ежемесячный платеж').fill('250 000');
  await page.getByLabel('Год выпуска, От').click();
  await page.getByLabel('Год выпуска, От').fill('2017');
  await page.getByLabel('Год выпуска, До').click();
  await page.getByLabel('Год выпуска, До').fill('2020');
  await page.getByLabel('Пробег, До').click();
  await page.getByLabel('Пробег, До').fill('150 000');
  await page.locator('.flex > div:nth-child(2) > div:nth-child(3)').click();
  await page.locator('div:nth-child(9) > div > .my-2').click();
  await page.getByRole('button', { name: 'Выбрать все' }).click();
  await page.getByLabel('Автомат').check();
  await page.getByLabel('Механика').check();
  await page.getByLabel('Седан').check();
  await page.getByLabel('Универсал').check();
  await page.getByLabel('Кроссовер').check();
  await page.getByLabel('Пикап').check();
  await page.getByLabel('Минивэн').check();
  await page.getByLabel('Электрический').check();
  await page.getByLabel('Бензиновый').check();
  await page.getByLabel('Гибридный').check();
  await page.getByLabel('Дизельный').check();
  await page.goto('https://mycar.kz/cars');
  await page.locator('div:nth-child(13) > div:nth-child(2) > .my-2').click();
  await page.getByLabel('Объем двигателя, От').click();
  await page.getByLabel('Объем двигателя, От').fill('2.');
  await page.getByLabel('increment').first().click();
  await page.getByLabel('Объем двигателя, От').click();
  await page.getByLabel('increment').first().click();
  await page.getByLabel('decrement').first().click();
  await page.getByLabel('Объем двигателя, До').click();
  await page.getByLabel('Объем двигателя, До').fill('3.');
  await page.getByLabel('increment').nth(1).click();
  await page.getByLabel('increment').nth(1).click();
  await page.getByLabel('Объем двигателя, До').click();
  await page.getByLabel('decrement').nth(1).click();
  await page.getByLabel('Белый').check();
  await page.getByLabel('Серебристый').check();
  await page.getByLabel('Черный').check();
  await page.getByLabel('Серый').check();
  await page.getByLabel('Золотистый').check();
  await page.getByLabel('Передний').check();
  await page.getByLabel('Задний').check();
  await page.getByLabel('Полный').check();
  await page.locator('div:nth-child(17) > div > .my-2').first().click();
  await page.locator('div:nth-child(17) > div:nth-child(2) > .my-2').click();
  await page.locator('div:nth-child(3) > .my-2').click();
  await page.goto('https://mycar.kz/cars');
  await page.getByRole('link', { name: 'Главная' }).click();
  await page.getByRole('contentinfo').getByRole('link', { name: 'Поиск авто' }).click();
  await page.getByRole('contentinfo').getByRole('link', { name: 'Создать объявление' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Автокредит' }).click();
  const page1 = await page1Promise;
  await page.getByRole('link', { name: 'Mycar Гид' }).click();
  await page.getByRole('link', { name: 'Профиль' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('link', { name: 'Мои объявления' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('link', { name: 'Избранное' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('link', { name: 'Настройки' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('link', { name: 'О компании' }).click();
  await page.getByRole('link', { name: 'Франшиза' }).click();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Пользовательское соглашение' }).click();
  const page2 = await page2Promise;
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Политика конфиденциальности' }).click();
  const page3 = await page3Promise;
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Сбор и обработка персональных данных' }).click();
  const page4 = await page4Promise;
});